### PR TITLE
block-patch fixes

### PR DESCRIPTION
**Pull request by SelfAdjointOperator**
fix misplaced closing bracket for wool flammability, missing prismarine flammability, pressure plate names in 1.13+

### CODE REVIEW

**Comment by SelfAdjointOperator** [comment]
I've also noticed a few 'patches' that seem unnecessary / yield the same result (eg packed_ice in 1.13?), however I am not committing them since I am pretty much completely changing the format of the colours JSON on my fork

**Comment by rebane2001** [comment]
Thanks, I'll add it soon. I will be rolling back your changes to weighted pressure plate named though - I'm going with what the vanilla game calls these blocks.

**Comment by SelfAdjointOperator** [comment]
I thought the weighted pressure plate names changed since the flattening?

**Comment by rebane2001** [comment]
Ah, you're right. I made the mistake of looking it up on google and [ending up here](https://minecraft.fandom.com/el/wiki/Weighted_Pressure_Plate#Crafting), which still used the old names. I didn't realize this was not the English wiki, so I just went with it.

**Pull request closed without merging**
